apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: pod-secret
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: primeiro-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: primeiro-secret
          key: password
