apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ensure-images-from-trusted-registry
#  namespace: aulas
spec:
  validationFailureAction: Enforce
  rules:
  - name: trusted-registry
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - new-aulas
    validate:
      message: "Somente images do repo da Chainguard"
      pattern:
        spec:
          containers:
          - name: "*"
            image: "cgr.dev/chainguard/*"
