apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-affinity
  name: nginx-affinity
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-affinity
  template:
    metadata:
      labels:
        app: nginx-affinity
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: nginx-affinity
              topologyKey: "kubernetes.io/hostname"
